version: '3.8'
services:

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stateDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  stats-server:
    build: stat-app/stat-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - POSTGRES_DB=stateDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stateDB
    restart: unless-stopped

  ewm-service:
    build: main-app
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:6541"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main