version: '3.8'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stateDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  stats-server:
    build: stat-app/stat-server
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - POSTGRES_DB=stateDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stateDB

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6543:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mainDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  main-service:
    build: main-app
    container_name: main-service
    depends_on:
      - main-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=mainDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATASOURCE_URL=jdbc:postgresql://main-db:5432/mainDB
      - STATS_SERVER=http://stats-server:9090